version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code/
      - static_volume:/code/staticfiles/
    ports:
      - "8000:8000"
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M

  db:
    image: postgres:13.0-alpine
    container_name: template-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER}"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  static_volume:
  postgres_data:
